// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using AZ_Desktop;
//
//    var guest = Guest.FromJson(jsonString);

namespace AZ_Desktop
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

  

    public partial class Guest
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("g_name")]
        public string G_name { get; set; }

        [JsonProperty("g_chip")]
        public string G_chip { get; set; }

        [JsonProperty("g_species")]
        public string G_species { get; set; }

        [JsonProperty("g_gender")]
        public string G_gender { get; set; }

        [JsonProperty("g_in_date")]
        public DateTimeOffset G_in_date { get; set; }

        [JsonProperty("g_in_place")]
        public string G_in_place { get; set; }

        [JsonProperty("g_out_date")]
        public DateTimeOffset G_out_date { get; set; }

        [JsonProperty("g_adoption")]
        public string G_adoption { get; set; }

        [JsonProperty("g_other")]
        public string G_other { get; set; }

        [JsonProperty("g_image")]
        public string G_image { get; set; }

        [JsonProperty("created_at")]
        public DateTimeOffset Created_at { get; set; }

        [JsonProperty("updated_at")]
        public DateTimeOffset Updated_at { get; set; }

        [JsonProperty("deleted_at")]
        public object Deleted_at { get; set; }

        public override string ToString()
        {
            return $"{this.G_species} - {this.G_name}";
        }
    }

    public enum G_species { kutya, macska };
    public enum G_gender { nőstény, hím, ismeretlen };
    public enum G_adoption { igen, nem };

    public partial class Guest
    {
        public static Guest[] FromJson(string json) => JsonConvert.DeserializeObject<Guest[]>(json, AZ_Desktop.Converter.Settings);
    }
    /***/
    

    /***** 1 *****/

    internal class G_speciesConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(G_species) || t == typeof(G_species?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "kutya":
                    return G_species.kutya;
                case "macska":
                    return G_species.macska;
            }
            throw new Exception("Cannot unmarshal type Gender");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (G_species)untypedValue;
            switch (value)
            {
                case G_species.kutya:
                    serializer.Serialize(writer, "kutya");
                    return;
                case G_species.macska:
                    serializer.Serialize(writer, "macska");
                    return;
            }
            throw new Exception("Cannot marshal type G_species");
        }

        public static readonly G_speciesConverter Singleton = new G_speciesConverter();
    }
    /***** 1 *****/

    /***** 2 *****/

    internal class G_genderConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(G_gender) || t == typeof(G_gender?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "nőstény":
                    return G_gender.nőstény;
                case "hím":
                    return G_gender.hím;
                case "ismeretlen":
                    return G_gender.ismeretlen;
            }
            throw new Exception("Cannot unmarshal type G_gender");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (G_gender)untypedValue;
            switch (value)
            {
                case G_gender.nőstény:
                    serializer.Serialize(writer, "nőstény");
                    return;
                case G_gender.hím:
                    serializer.Serialize(writer, "hím");
                    return;
                case G_gender.ismeretlen:
                    serializer.Serialize(writer, "ismeretlen");
                    return;
            }
            throw new Exception("Cannot marshal type G_gender");
        }

        public static readonly G_genderConverter Singleton = new G_genderConverter();
    }

    /***** 2 *****/

    /***** 3 *****/

    internal class G_adoptionConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(G_adoption) || t == typeof(G_adoption?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "igen":
                    return G_adoption.igen;
                case "nem":
                    return G_adoption.nem;
            }
            throw new Exception("Cannot unmarshal type G_adoption");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (G_adoption)untypedValue;
            switch (value)
            {
                case G_adoption.igen:
                    serializer.Serialize(writer, "igen");
                    return;
                case G_adoption.nem:
                    serializer.Serialize(writer, "nem");
                    return;
            }
            throw new Exception("Cannot marshal type G_adoption");
        }

        public static readonly G_adoptionConverter Singleton = new G_adoptionConverter();
    }

    /***** 3 *****/

}










/*
using Org.BouncyCastle.Crypto.Digests;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AZ_Desktop
{
    public class Guest
    {
        int id;
        string g_name;
        string g_chip;
        string g_species;
        string g_gender;  
        DateTime g_in_date;    
        string g_in_place;
        DateTime g_out_date;    
        string g_adoption; 
        string g_other;
        byte[] g_image; 
        DateTime created_at;
        DateTime updated_at;

        public Guest()
        {
            this.Created_at = DateTime.Now; // Az objektum létrehozásának időpontja
            this.Updated_at = DateTime.Now; // Az utolsó frissítés időpontja
        }

        public Guest(int id, string g_name, string g_chip, string g_species, string g_gender, DateTime g_in_date, string g_in_place, DateTime g_out_date, string g_adoption, string g_other, byte[] g_image, DateTime created_at, DateTime updated_at)
        {
            this.Id = id;
            this.G_name = g_name;
            this.G_chip = g_chip;
            this.G_species = g_species;
            this.G_gender = g_gender;
            this.G_in_date = g_in_date;
            this.G_in_place = g_in_place;
            this.G_out_date = g_out_date;
            this.G_adoption = g_adoption;
            this.G_other = g_other;
            this.G_image = g_image;
            this.Created_at = created_at;
            this.Updated_at = updated_at;
        }

        public int Id { get => id; set => id = value; }
        public string G_name { get => g_name; set => g_name = value; }
        public string G_chip { get => g_chip; set => g_chip = value; }
        public string G_species { get => g_species; set => g_species = value; }
        public string G_gender { get => g_gender; set => g_gender = value; }
        public DateTime G_in_date { get => g_in_date; set => g_in_date = value; }
        public string G_in_place { get => g_in_place; set => g_in_place = value; }
        public DateTime G_out_date { get => g_out_date; set => g_out_date = value; }
        public string G_adoption { get => g_adoption; set => g_adoption = value; }
        public string G_other { get => g_other; set => g_other = value; }
        public byte[] G_image { get => g_image; set => g_image = value; }
        public DateTime Created_at { get => created_at; set => created_at = value; }
        public DateTime Updated_at { get => updated_at; set => updated_at = value; }

        public override string ToString()
        {
            /*string species = string.IsNullOrEmpty(this.G_species) ? "Nincs? Probléma a fajtával" : this.G_species;
            string name = string.IsNullOrEmpty(this.G_name) ? "Nincs? Probléma a névvel!" : this.G_name;*/
/*         return $"{this.G_species} - {this.G_name}";
     }
 }
}
*/